### ISSUE TITLE
Task Memory and Task Milestones

### ISSUE THREAD

**Issue by matannahmani** [kodu-ai/claude-coder#32]
Improve our internal prompting by adding Internal Task Memory and Task Milestones.

- [ ] New Prompts for breaking the task into smaller milestones and automatically updating task memory
- [ ] Task Memory UI
- [ ] Task Memory Storage
